bookapp_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('users/',include('django.contrib.auth.urls')),
    path('',include('pages.urls')),
    path('books/',include('books.urls')),
    path('categories/',include('categories.urls')),
    path('authors/',include('authors.urls')),
    path("publishers/", include("publishers.urls")),
    path("reviews/", include("reviews.urls")),
    path("comments/", include("comments.urls")),
    path("search/",include("search.urls")),
]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

books/urls.py
from django.urls import path
from .views import (
    BookListView, 
    BookUpdateView, 
    BookDetailView, 
    BookDeleteView, 
    BookCreateView,
)
   

urlpatterns = [
    path('',BookListView.as_view(), name='books'),
    path('<int:pk>/edit/',BookUpdateView.as_view(), name='book_edit'),
    path('<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('<int:pk>/delete/',BookDeleteView.as_view(), name='book_delete'),
    path('new/', BookCreateView.as_view(), name="book_new"),
    
]

authors/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Author(models.Model):
    name = models.CharField(("author name"), max_length=80)
    biography = models.TextField(("biography"),blank=True)
    image = models.ImageField(upload_to="images/authors", blank=True)
   
    class Meta:
        verbose_name = "author"
        verbose_name_plural = "authors"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("author_detail", kwargs={"pk": self.pk})

templates/account.html
{% extends 'base.html' %}
{% block title %} <title>Boogle | account settings </title> {% endblock %}

{% block content %}
<style>
    table{border-spacing:30px}
    td > a{text-decoration:none}
    tr,td{border:none;margin-top:25px;}
    .user-icon{font-size:23px;margin-right:10%}
    .nav{padding:10px 30px 0px 0px}
</style>
  {% include 'nav.html' %}
  <div class='container-fluid pt-5 ps-5'>
      <div class='row'>
        <h2>Your account </h2>
        <hr style='background-color:gainsboro'>
          <div class='col-md-12'>
              <table class='col-md-12 table'>
                  <tr style='margin-top:30px'>
                      <td style='margin-top:30px'>{{ user.email }}</td>
                      <td><a href="#" class='d-flex justify-content-end'>Change Email</td>
                  </tr>
                  <tr class=''>
                    <td>Password:******</td>
                    <td><a href="{% url 'password_change' %}" class='d-flex justify-content-end'>Change My password</td>
                  </tr>
                  <tr class='tr'>
                    <td>Name: {{ user.username}}</td>
                    <td><a href="#" class='d-flex justify-content-end '>Change Details</td>
                  </tr>
              </table>
          </div>
      </div>
      <div class='row pt-3'>
        <h2>Searching Hystory </h2>
        <hr style='background-color:gainsboro'>
        <div class='col-md-12'>
            <table class='col-md-12 table'>
                <tr style='margin-top:30px'>
                    <td style='margin-top:30px'>{{ user.email }}</td>
                    <td><a href="#" class='d-flex justify-content-end'>Change Email</td>
                </tr>
                <tr class=''>
                  <td>Password:******</td>
                  <td><a href="#" class='d-flex justify-content-end'>Change My password</td>
                </tr>
                <tr class='tr'>
                  <td>Name: {{ user.username}}</td>
                  <td><a href="#" class='d-flex justify-content-end '>Change Details</td>
                </tr>
            </table>
        </div>
    </div>
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE HTML>
{% load static %}
<html>
    <head>
        <meta charset='UTF-8'>
        <title>{{ page_title }}</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link href="{% static 'css/style.css' %}" rel="stylesheet"/>
    </head>
    <body>
        <main>
        {% block content %}
        {% endblock content %}
        </main>
    </body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/fe93394798.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="{% static 'js/index.js' %}"></script>
</html>

templates/dropdown.html
<style>
    #dropdown{
      margin-top:25px;
      border-radius:0px;
      
    }
    .user-icon{padding:5px 5px 5px 5px;}
    .dropdown-item{color:black;font-size:18px;}
    .dropdown-icon{font-size:20px}
</style>


<div class='dropdown dropstart'>
    {% if user.is_authenticated %}
    <a class='user-icon text-white' id='dropdownMenuLink' data-bs-toggle="dropdown" aria-expanded="false" href='#'><i class="fa-solid fa-circle-user"></i></a>
    <ul class="dropdown-menu  bg-light border border-light" aria-labelledby="dropdownMenuLink" id="dropdown">
     <li class="nav-item">
         <a class="dropdown-item nav-link" href="{% url 'account' %}">
            <i class="fa-solid fa-gear dropdown-icon"></i>
            <span>Settings</span>
         </a>
     </li>
     {% if user.is_staff %}
      <li class="nav-item">
          <a class="dropdown-item nav-link" href="{% url 'books' %}">
             <i class="fa-solid text-dark   fa-gauge dropdown-icon"></i>
             <span>Dashboard</span>
          </a>
      </li>
     {% endif %}
     <li class="nav-item">
         <a class="dropdown-item nav-link" href="{% url 'logout' %}">
             <i class="fa-solid text-dark fa-arrow-right-from-bracket dropdown-icon"></i> 
             <span>Logout</span>
         </a>
     </li>
     
   </ul>
</div>

{% else %}
<a class='btn btn-dark btn-sm btn-login' href="{% url 'login' %}">Sign in</a>
{% endif %}

templates/header.html
<header>
    <nav class='nav d-flex justify-content-end'>
       {% include 'nav.html' %}
    </nav>
</header>

templates/home.html
{% extends 'base.html' %}
{% load search_tags %}
{% block content %}
{% if user.is_authenticated %}
  <nav class='navbar navbar-expand-lg navbar-white justify-content-end pt-3'>
    <div class='dropdown dropstart' style="margin-right:10%">
        <a class='user-icon text-dark' id='dropdownMenuLink' data-bs-toggle="dropdown" aria-expanded="false" href='#'><i class="fa-solid fa-circle-user"></i></a>
        <ul class="dropdown-menu  bg-dark border border-light" aria-labelledby="dropdownMenuLink" id="dropdown">
         <li class="nav-item">
             <a class="dropdown-item nav-link" href="{% url 'account' %}">
                <i class="fa-solid fa-gear dropdown-icon"></i>
                <span>Settings</span>
             </a>
         </li>
         {% if user.is_staff %}
          <li class="nav-item">
              <a class="dropdown-item nav-link" href="{% url 'books' %}">
                 <i class="fa-solid   fa-gauge dropdown-icon"></i>
                 <span>Dashboard</span>
              </a>
          </li>
         {% endif %}
         <li class="nav-item">
             <a class="dropdown-item nav-link" href="{% url 'logout' %}">
                 <i class="fa-solid fa-arrow-right-from-bracket dropdown-icon"></i> 
                 <span>Logout</span>
             </a>
         </li>
       </ul>
    </div>
    {% else %}
    <div class="container d-flex justify-content-end pt-3">
        <a class='btn btn-dark btn-sm btn-login' href="{% url 'login' %}">Sign in</a>
    </div>
    {% endif %}
</nav>
<div class='container-fluid pt-2'>
    <div class="d-flex justify-content-center">
        {% search_box request %}
    </div>
</div>
{% endblock %}

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-white bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Boogle</a>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active text-white" aria-current="page" href="{% url 'home' %}">Home</a>
          </li>
          {% if user.is_staff %}
            <li class='nav-item'>
              <a class="nav-link text-white" href="{% url 'books' %}">Books</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'category_list' %}">Categories</a>
            </li>
            <li class="nav-item">
               <a class="nav-link text-white" href="{% url 'author_list' %}">Authors</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'publisher_list' %}">Publishers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'review_list' %}">Reviews</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-white" href="{% url 'comment_list' %}">Comments</a>
            </li>
            {% endif %}
        </ul>
      </div>
      {% include 'dropdown.html' %}
      </div>
    </div>
  </nav>

templates/search_results.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
  <nav class='navbar navbar-expand-lg navbar-white justify-content-end pt-3'>
    <div class='dropdown dropstart' style="margin-right:10%">
        <a class='user-icon text-dark' id='dropdownMenuLink' data-bs-toggle="dropdown" aria-expanded="false" href='#'><i class="fa-solid fa-circle-user"></i></a>
        <ul class="dropdown-menu  bg-dark border border-light" aria-labelledby="dropdownMenuLink" id="dropdown">
         <li class="nav-item">
             <a class="dropdown-item nav-link" href="{% url 'account' %}">
                <i class="fa-solid fa-gear dropdown-icon"></i>
                <span>Settings</span>
             </a>
         </li>
         {% if user.is_staff %}
          <li class="nav-item">
              <a class="dropdown-item nav-link" href="{% url 'books' %}">
                 <i class="fa-solid   fa-gauge dropdown-icon"></i>
                 <span>Dashboard</span>
              </a>
          </li>
         {% endif %}
         <li class="nav-item">
             <a class="dropdown-item nav-link" href="{% url 'logout' %}">
                 <i class="fa-solid fa-arrow-right-from-bracket dropdown-icon"></i> 
                 <span>Logout</span>
             </a>
         </li>
       </ul>
    </div>
    {% else %}
    <div class="container d-flex justify-content-end pt-3">
        <a class='btn btn-dark btn-sm btn-login' href="{% url 'login' %}">Sign in</a>
    </div>
    {% endif %}
</nav>
<div class='container-fluid '>
    <div class="">
        <div class="col-md-8 container">
            <form method='get' class='' action="{% url 'search_results' %}">
                <h1 class="site-title">boogle</h1>
                <div>
                    <input type='search' name="q" value="{{q}}" class='search form-control' placeholder='search book name'/>
                </div>
                <div>
                    <button id="btn-search" class='btn btn-primary mt-3 border-0' type='submit'>Search</button>
                </div>
            </form>
        </div>
    </div>
    <div>
        <div class="col-md-8 container mt-3">
           <!--- When no book matching search term is found -->
           {% if not count %}
           <h5 class="text-muted">Sorry we could no find any book matching <span class="text-info">{{q}}</span></h5>
           
           {% else %}

           <!-- When there are books matching search term -->
           {% for book in book_list %}
                <div class="row">
                    <div class="col-md-3">
                        <img src="{{book.image.url}}" class="rounded float-left img-thumbnail" style="max-width:12em">
                    </div>
                    <div class="col-md-6">
                        <a href="{% url 'book_detail' book.pk %}" class="link ms-0">{{ book.title }}</a>
                        <p> author :
                            {% for author in book.author.all %}
                                <a href="{% url 'search_author_detail' author.pk %}" class="link">
                                    <span>{{ author.name }}</span>,
                                </a>
                            {% endfor %}
                        </p>
                        <p style="text-align:justify">{{ book.description| truncatewords:60}} </p>
                        <a href="{% url  'book_detail' book.pk %}" class="link ms-0">Read more</a>
                    </div>
                </div>
                <hr>
            {% endfor %}
            <!-- we displayed all matching books -->
              <!--- pagination -->
              <ul class="pagination">
                {% if book_list.has_previous %}
                    <li class="page-item"><a href="?page=1" class="page-link"></a></li>
                {% endif %}
                    <li class="page-item"><a href="" class="page-link">Page {{book_list.number}} of {{book_list.paginator.num_pages}}</a>
                {% if book_list.has_next %}
                    {% for i in nums %}
                        <li class="page-item"><a href="?page={{forloop.counter}}" class="page-link">{{forloop.counter}}</a></li>
                    {% endfor %}
                {% endif %}
            </ul>
            <!-- end pagination -->
            {% endif %}
        </div>
    </div>
</div>


{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% bootstrap_messages %}

{% block title %}Sign up {% endblock %}
{% block content %}

<div class='container col-md-4 ps-0'>
    <h2>Sign up for a new account </h2>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class='btn btn-primary' type='submit'>Sign up</button>
    </form>
    <p>already have an account <a href="{% url 'login' %}" style='text-decoration:none'>Sign in</a></p>
</div>

{% endblock %}